### ISSUE TITLE
Can't reproduce example

### ISSUE THREAD

**Issue by TimFruition** [sentinel-hub/sentinel2-cloud-detector#13]
Hi ! I'm trying to reproduce the example by copying exactly commands from `sentinel2-cloud-detector-example.ipynb`
But the result isn't as good.

Somebody has an idea why I have this result?

![capture d ecran 2018-11-19 a 16 44 33](https://user-images.githubusercontent.com/28758847/48717818-715c9d80-ec1a-11e8-9f03-6b01cd7b4f15.png)

**Comment by AleksMat** [comment]
This issue was resolved in [forum](https://forum.sentinel-hub.com/t/cant-reproduce-github-s2cloudless-examples/628).

We also added more explanations in example notebook and released a new package version `1.2.2` with some automatic disabling of atmospheric correction.
