### ISSUE TITLE
joblib problem

### ISSUE THREAD

**Issue by albhasan** [sentinel-hub/sentinel2-cloud-detector#17]
Good afternoon,

I'm installing s2cloudless but I'm getting the error below:

``import s2cloudless``
``/home/scidb/miniconda2/envs/s2cloudless/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.``
``  warnings.warn(msg, category=DeprecationWarning)``
``Segmentation fault (core dumped)``

I'm running a Ubuntu 14.04.5 LTS server with Python 3.7.3 inside a conda environment and I have no clue what I'm doing wrong. Thanks!

**Comment by AleksMat** [comment]
Hi @albhasan,

If I could guess I would say that `pyproj` package might be the cause. Lately there have been a few unstable releases which cause exacty such segmentation faults. Could you try running
```Python
import pyproj
```
If this turns out to be the reason, try upgrading or downgrading `pyproj` until it works.

**Comment by albhasan** [comment]
Hi,

I re-created my python environment from scratch, later I updated python's packages pip & joblib and finally I installed s2cloudless by hand. It is working now. Thanks for your kind answer.

Bests,
