### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by sbdelahaies** [sentinel-hub/sentinel2-cloud-detector#22]
Dear sentinel-hub team,

I am running ubuntu 19.04, python3.7 (via spyder most of the time). I installed all the packages (sentinelhub, eo-learn, ...) using pip3. 

I am having troubles running the sentinel2-cloud-detector example. All cloud pictures come black. 
Similarly when I run the eo-learn  land cover map classification, the parts involving cloud mask (IS_VALID mask, CLM and CLP data) do not produce the expected results.

I tried to run the test_all.py for s2cloudless but the execution failed, errors like "Layer S2-DOS1 not found" come up, but not only.

I tried to install s2cloudless using the setup.py script. Running the script 

python3 setup.py build 

produces a warning, I had to change "include s2cloudless/TestInputs/*" to  "include tests/TestInputs/*" in the MANIFEST.in file. 
Then when I run
  
python3 setup.py install

everything goes smoothly until I get final statement:  

Installed /usr/local/lib/python3.7/dist-packages/s2cloudless-1.4.0-py3.7.egg
Processing dependencies for s2cloudless==1.4.0
error: oauthlib 2.1.0 is installed but oauthlib>=3.0.0 is required by {'requests-oauthlib'}

it keeps complaining about oauthlib 2.1.0 which is not installed on my machine, oauthlib 3.1.0 is installed. I uninstalled and reinstalled a couple of times this package without success. 

Would you have any idea how to this issue?

I also encountered another problem when I run sentinelhub. After a fresh install of all the packages I get an error message involving the file transformer.py in the pyproj package . In order to get it to work I have to change "direction=TransformDirection.FORWARD" to "direction='FORWARD'" in the transformer.py file, I doubt it but I don't know if this could be the reason why s2cloudless does complete installation properly.

Sorry for the messy post, I can provide any further information.

Best regards

**Comment by AleksMat** [comment]
Some notes regarding these issues:

- `oauthlib` and `requests-oauthlib` are dependecies of `sentinelhub-py`. Both packages should be upgraded to avoid issues.
- Issues with `pyproj` package should be addressed in `pyproj` repo.
- Running tests in this package is now being simplified and will not require any Sentinel Hub layers from the configuration.

I'll close this issue for now but feel free to reopen if any of this is still a problem.
