### ISSUE TITLE
Relicense to a non-Creative Commons license meant for software

### ISSUE THREAD

**Issue by kylebarron** [sentinel-hub/sentinel2-cloud-detector#24]
Creative Commons [recommends against](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) using a Creative Commons license for software:

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses listed as free by the Free Software Foundation and listed as “open source” by the Open Source Initiative.
> 
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

More discussion about why CC BY-SA is discouraged for software is [available on StackOverflow](https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code).

Would you be interested in relicensing to [an open-source license designed for code](https://opensource.org/licenses)?

**Comment by AleksMat** [comment]
The standard policy in our company remains that we use MIT license for code and Creative Commons for ML models. Because this package is basically a ML model wrapped in a bit of Python code, it will for now stay licensed as Creative Commons.
