### ISSUE TITLE
NewConnectionError

### ISSUE THREAD

**Issue by omarghattas** [sentinel-hub/sentinel2-cloud-detector#3]
how do i deal with this error:

INFO:sentinelhub.download:Download attempt failed with HTTPConnectionPool(host='opensearch.sentinel-hub.com', port=80): Max retries exceeded with url: /resto/api/collections/Sentinel2/search.json?box=-90.92164993286133%2C14.419052876760505%2C-90.81865310668945%2C14.55201636533031&index=1&startDate=2017-12-01T00%3A00%3A00&completionDate=2017-12-31T23%3A59%3A59&maxRecords=500 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58d7a7bd68>: Failed to establish a new connection: [Errno 110] Connection timed out',))
INFO:sentinelhub.download:Download attempt failed with HTTPConnectionPool(host='opensearch.sentinel-hub.com', port=80): Max retries exceeded with url: /resto/api/collections/Sentinel2/search.json?box=-90.92164993286133%2C14.419052876760505%2C-90.81865310668945%2C14.55201636533031&index=1&startDate=2017-12-01T00%3A00%3A00&completionDate=2017-12-31T23%3A59%3A59&maxRecords=500 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58d7ad90f0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

when running this code:

wms_true_color_request = WmsRequest(layer=LAYER_NAME,
                                    bbox=bounding_box, 
                                    time=('2017-12-01','2017-12-31'), 
                                    width=600, height=800,
                                    image_format=MimeType.PNG,
                                    instance_id=INSTANCE_ID)
wms_true_color_imgs = wms_true_color_request.get_data()

**Comment by blazs** [comment]
Hi @omarghattas,

all is fine as far as the Python package is concerned. The error that you're seeing is caused by the failure on the services side. I suggest that you simply try to rerun the code.

**Comment by omarghattas** [comment]
I've got an instance ID, I wasn't so sure how to choose the layer_name, I currently have `LAYER_NAME='Agriculture'` but still throws the following error:

> RuntimeError: Failed to obtain json from http://opensearch.sentinel-hub.com/resto/api/collections/Sentinel2/search.json?box=-90.92164993286133%2C14.419052876760505%2C-90.81865310668945%2C14.55201636533031&index=1&startDate=2017-12-01T00%3A00%3A00&completionDate=2017-12-31T23%3A59%3A59&maxRecords=500

**Comment by azupanc** [comment]
@omarghattas Can you try again? And if it sill doesn't work can you give us an example WMS or WCS request that fails so that we can investigate further?
