### ISSUE TITLE
how to manipulate threshold, average_over, dilation_size

### ISSUE THREAD

**Issue by aksaxena09** [sentinel-hub/sentinel2-cloud-detector#30]
hey please let me know 
1. how I can decide these 3 parameters (threshold, average_over, dilation_size) if I am using 20m resolution image ?
2. Can I use this package for 10m resolution or not?
3. there is decrease in vegetation indices due to cloud or shadow so is there a way to find out this decrease error in the vegetation indices like ndvi or savi?

**Comment by batic** [comment]
1) This really depends on your use-case. The reason for these 3 parameters is that user can tweak them according to their needs: is it really important that all clouds are detected: lower the threshold and increase average_over and dilation_size. Is it ok if some clouds are still present, but that the false positives are low: increase the threshold. The average_over and dilation_size can also help a bit when dealing with small clouds (like in tropics). So please try a few options and see what works best for you. 

2) Yes. The model works on "any" resolution: we've been using it on 10m (and so is Google Earth Engine, where they use s2cloudless to produce cloud masks at 10m), but we've also used it on objects: aggregated (i.e. averaged) data over polygons.

3) NDVI is fairly robust to shadows, but again, if you are after a very clean data, you might have to remove shadows yourself. Unfortunately, the s2cloudless only removes clouds. For more on uncertainty of NDVI see also https://custom-scripts.sentinel-hub.com/sentinel-2/ndvi_uncertainty/

**Comment by aksaxena09** [comment]
Can we use less than 10 bands in cloud detector to classify the images?

**Comment by batic** [comment]
No. The model in this library needs at least 10 bands:

```python
['B01', 'B02', 'B04', 'B05', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']
```

But you can retrieve `CLM` and `CLP` "bands" from SentinelHub services, which were created with s2cloudless. See more [info](https://docs.sentinel-hub.com/api/latest/user-guides/cloud-masks/).

**Comment by aksaxena09** [comment]
when we download sentinel tile there are only 7 band images in 10m resolution folder. so how can we use them to calculate CLP?

**Comment by batic** [comment]
Yes, Sentinel-2 bands have different resolutions. If you want to run the cloud masking at 10 m, upscale the lower resolution bands to 10 m. In Sentinel-Hub the default upscaling is "nearest neighbour". You can of course also downscale 10 m bands to 20 m and run s2cloudless on 20 m etc.
