### ISSUE TITLE
error on s2 dates 2016 or earlier

### ISSUE THREAD

**Issue by s-razavi** [sentinel-hub/sentinel2-cloud-detector#31]
First of all, great work, thank you.
On early days of S2 up to almost 2017, it returns the error:

`Image.select: Pattern 'probability' did not match any bands.`

You can check this by changing 2020 to 2016 in the colab and error pops up.
https://colab.research.google.com/github/google/earthengine-community/blob/master/tutorials/sentinel-2-s2cloudless/index.ipynb

**Comment by AleksMat** [comment]
Hi @s-razavi,

Great to see you find s2cloudless useful.

I don't have all information about the issue but I suspect that s2cloudless dataset on GEE has been created only for Sentinel-2 data from 2017 onward. The processing has been done by Google developers who wrote [this article](https://medium.com/google-earth/more-accurate-and-flexible-cloud-masking-for-sentinel-2-images-766897a9ba5f) and not by Sentinel Hub team. Therefore, I recommend asking them for details.

In case GEE really doesn't have data prior to 2017, there are also other ways of obtaining cloud masks for early time periods:

- you can obtain preprocessed cloud mask and probabilities from Sentinel Hub service for the entire archive ([docs](https://docs.sentinel-hub.com/api/latest/user-guides/cloud-masks/)),
- you can use the model from this package to process cloud masks for any time period yourself.
