### ISSUE TITLE
Replicate Cloud Probability in Python

### ISSUE THREAD

**Issue by mingardiluca** [sentinel-hub/sentinel2-cloud-detector#44]
I am trying to compute the cloud probability of a territory in Ivory Coast in python using s2cloudless, and the result that I get is different than that using the snippet of code found [here](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_CLOUD_PROBABILITY). 
The only modifications that I made to the above script are:
var START_DATE = ee.Date('2022-09-21');
var END_DATE = ee.Date('2022-09-22'); # The date of interest is September 21st 2022
var MAX_CLOUD_PROBABILITY = 101; # this is to show the entirity of the original image (clouds included)
var region =
    ee.Geometry.Rectangle({coords: [-4.310415, 6.037586, -4.211883, 6.136218], geodesic: false}); # Area of interest 
Map.setCenter(-4.25, 6.1, 12);

In python, basically the entire image is predicted to have a probability of clouds of about 100%; in GEE, such probability is much lower for some areas of the image. My understanding is that GEE uses the s2cloudless algorithm for the computed probabilities in 'COPERNICUS/S2_CLOUD_PROBABILITY', so i don't understand why the result would be different when computed in python.

Thank you

Files in the zip file:
- `tiffs` is the folder containing the tiffs that I dowloaded in python from the Sentinel API
- `code.py` is a snipped of code to replicate my results
- `python.png` is the image resulting from the tiffs, collected in python
- `GEE_thresh_101.png` is a screenshot of GEE when MAX_CLOUD_PROBABILITY is set to 101
- `GEE_thresh_30.png` is a screenshot of GEE when MAX_CLOUD_PROBABILITY is set to 30 (you can see that there are some parts of the image that haven't been removed, meaning that the cloud probability is less than 30%)
- `image.pdf` has on the left the python image and on the right the cloud probability, computed in python

[experiment.zip](https://github.com/sentinel-hub/sentinel2-cloud-detector/files/10450001/experiment.zip)

**Comment by batic** [comment]
Hi @mingardiluca 

Your question would probably best be asked at the GEE forums, but I'll have a look and try to answer in the next few days.

**Comment by batic** [comment]
I've tried rerunning this using sh-py (using bbox from your tiffs, and requesting dates `2022-09-21..2022-09-22`, and I get this:
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/2518145/213484197-1eacb29b-26eb-4f03-9d6b-0b581fab2c51.png">


Comparing your tiff data with data downloaded from SH, I see your data is skewed (see below). Did you perhaps download data using some scaling factor?

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/2518145/213484463-c2497ee4-452f-487d-91ee-b52bbe397a04.png">

I'm attaching a notebook I've used; hope it helps. 
[s2cloudless_gee.ipynb.zip](https://github.com/sentinel-hub/sentinel2-cloud-detector/files/10458214/s2cloudless_gee.ipynb.zip)

**Comment by batic** [comment]
Just to add: if the bands that are input to s2cloudless are scaled, then your results are expected. The input to s2cloudless should be raw data from Sentinel-2 L1C.

**Comment by mingardiluca** [comment]
Hi @batic! 
First of all, thank you very much for your quick answer.

I've been investigating what you highlighted, by inspecting how I get the data from the beginning of my pipeline. I don't get the data from SentinelHubInputTask, I retrieve the data from Google Cloud, in this case [here](https://storage.googleapis.com/gcp-public-data-sentinel-2/tiles/30/N/UM/S2A_MSIL1C_20220921T102731_N0400_R108_T30NUM_20220921T155246.SAFE_%24folder%24). I found online that after January 25th 2022, the bands have been shifted by 1000 (hence your plot of distributions), according to [this](https://github.com/sentinel-hub/sentinel2-cloud-detector#input-sentinel-2-scenes) and [this](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED): 
"After 2022-01-25, Sentinel-2 scenes with PROCESSING_BASELINE '04.00' or above have their DN (value) range shifted by 1000. The HARMONIZED collection shifts data in newer scenes to be in the same range as in older scenes.".
Apparently this shift is taken care of directly by SentinelHub and GEE, but I have to modify it manually in order to have the same results as you (image below).
This is my output when removing 1000 from each band
<img width="739" alt="mine" src="https://user-images.githubusercontent.com/54487859/213534477-827efaaa-637e-4e20-a139-03e592a338c6.png">

This is a screenshot from the notebook you sent over
<img width="731" alt="yours" src="https://user-images.githubusercontent.com/54487859/213534576-72ff3161-2bb7-493b-9aa7-08559eb5391b.png">

The results are very similar, and in line with what I saw in GEE. Does it makes sense to proceed as I explained (for data retrieved after 25-01-2022, remove 1000 for each band), or something additional is needed?

Thank you very much

**Comment by batic** [comment]
s2cloudless model has been trained on data prior to the changes in processing baseline from ESA, so the correct way is to make the input to the model exactly like before. The Sentinel-Hub service does that for you, see also [this post](https://forum.sentinel-hub.com/t/sentinel-2-processing-baseline-changes-and-harmonizevalues/4635), I am not sure how you need to apply this in GEE, but your thinking is correct. 

In addition (again, see the post above), you should clamp the negative values to 0, as the model never saw negative values as input.

If that answers your questions, please close the issue.

**Comment by eoasker** [comment]
@mingardiluca is there any way you could post the final code here? I am having issues with using the package locally. I am dividing my bands by 10000.0 but do I also need to remove 10000 from them?
