### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by jaimebayes** [sentinel-hub/sentinel2-cloud-detector#6]
Hi, 
I am trying to install s2cloudless package into Anaconda python3.6 Win10 64-bit installation.
Using pip install s2cloudless generates a pile of errors.
Any suggestion? 
Thanks, Jaime

**Comment by blazs** [comment]
Hi Jaime,

could you provide more details (e.g. paste the error trace)?

**Comment by jaimebayes** [comment]
Hi Blazs, 
I installed it cloning, and then python install setup.py.
I did not work using pip install s2cloudless, no clue why.
Thanks, Jaime
