### ISSUE TITLE
s2cloudless not working on environment

### ISSUE THREAD

**Issue by EmanuelCastanho** [sentinel-hub/sentinel2-cloud-detector#67]
I am using `S2PixelCloudDetector` from `s2cloudless`, but I am having a `zsh: segmentation fault` error when running `get_cloud_probability_maps`. The problem seems to be from the environment, but I don't know how to solve it, I already changed the order of installation.

It works fine for the following environment:

```
conda install -c conda-forge gdal=3.5.0 geopandas=0.11.1 lightgbm=3.3.2

pip install python-dotenv==0.20.0 sentinelsat==1.1.1 zipfile36==0.1.3 netCDF4==1.5.8 pyproj==3.3.1 scikit-image==0.19.2 pyhdf==0.10.5 --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-packages/simple terracatalogueclient==0.1.11 matplotlib==3.5.2 y pandas==1.4.3 scikit-learn==1.1.1 ubelt==1.1.2 s2cloudless==1.6.0 rasterio==1.3.0.post1 hummingbird-ml==0.4.5 julia==0.6.0 xgboost==1.7.3 
```

But gives error when adding Pytorch:

```
conda install -c conda-forge gdal=3.5.0 geopandas=0.11.1 lightgbm=3.3.2

pip install python-dotenv==0.20.0 sentinelsat==1.1.1 zipfile36==0.1.3 netCDF4==1.5.8 pyproj==3.3.1 scikit-image==0.19.2 pyhdf==0.10.5 --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-packages/simple terracatalogueclient==0.1.11 matplotlib==3.5.2 y pandas==1.4.3 scikit-learn==1.1.1 ubelt==1.1.2 s2cloudless==1.6.0 rasterio==1.3.0.post1 hummingbird-ml==0.4.5 julia==0.6.0 xgboost==1.7.3 

conda install -c pytorch pytorch=1.13.1 torchvision=0.14.1 torchaudio=0.13.1
```

Any suggestions?

**Comment by batic** [comment]
Hi @EmanuelCastanho 

`s2cloudless` doesn't require PyTorch, so no need to install it to run `s2cloudless`. Does the error also happen if you don't have torch installed in your environment?

**Comment by EmanuelCastanho** [comment]
Hello @batic 
I know that, but my project uses all the dependencies that I listed, including PyTorch :)
The error doesn't happen when I don't have torch installed in the environment.

**Comment by batic** [comment]
Sorry @EmanuelCastanho,

The questions regarding installation of `pytorch` are probably best asked somewhere else (e.g. on pytorch forum). Additionally, regardless if this is torch problem, or problem of a combination of torch with other dependencies on your list, the `zsh: segmentation fault` error is probably not enough info.

PS: I'll keep the question open for some more time if somebody else from the community can provide more help.
