### ISSUE TITLE
Download the cloudmasks

### ISSUE THREAD

**Issue by Johannes-R-Schmid** [sentinel-hub/sentinel2-cloud-detector#7]
Dear Sinergise,

if I use your cloudmask (s2cloudless), I get two arrays, the cloud mask and cloud probability mask for each timestep. Did you include a function such as get_data(save_data=True) to save those arrays similar to the WcsRequest function, because if I want to do that on my own I would need geotransformation and projection information to save the numpy arrays as geotiffs. Although, I could find a workaround, I wanted to ask you first, if I overlooked a functionality of your service.

Greetings Johannes

**Comment by azupanc** [comment]
The question was answered at Sentinel Hub's forum: https://forum.sentinel-hub.com/t/download-of-s2cloudless-results/228/2?u=anze.zupanc.
