### ISSUE TITLE
How many Antarctic scenes were used to train s2cloudless?

### ISSUE THREAD

**Issue by KimBaldry** [sentinel-hub/sentinel2-cloud-detector#78]
Hello!

Just wondering how many Antarctic scenes were used to train s2cloudless?

**Comment by zigaLuksic** [comment]
Hi, no Antarctic scenes were used.
Location of training data is also shown [here](https://medium.com/sentinel-hub/improving-cloud-detection-with-machine-learning-c09dc5d7cf13)
