### ISSUE TITLE
OpenCV 3.4.0.14 requirement

### ISSUE THREAD

**Issue by nargiropgeo** [sentinel-hub/sentinel2-cloud-detector#8]
While installing the library I am asked to install the OpenCV 3.4.0.14 version specifically. I can't seem to find it anywhere, since ver. 3.4.1 was released. For that reason, I can't install this library.

**Comment by nargiropgeo** [comment]
Hi,

I already tried and I get an error saying that no matching distribution has
been found. I tried downloading an older release from the OpenCV GitHub,
but for some reason it only includes the python27 module.

**Comment by nargiropgeo** [comment]
By the way, I am using windows. Not Linux.

**Comment by AleksMat** [comment]
It looks like on Windows there might be some additional trick. But in general `opencv-python==3.4.0.14` is available on PyPI (with some instructions): https://pypi.org/project/opencv-python/3.4.0.14/ so it should be possible to install it.

Have you tried uninstalling your current version of `opencv-python` before installing the new one? Are you using Python version `>=3.5`? Could you maybe write here the exact error message you are getting?

To explain a bit further this package dependency - the `s2cloudless` package requires package `sentinelhub` which requires `opencv-python==3.4.0.14` for [reading 15-bit JPEG2000 files](https://github.com/sentinel-hub/sentinelhub-py/issues/33). That functionality of `sentinelhub` however is not actually required by `s2cloudless`. So if nothing else would work you could also download `sentinelhub` from the [source](https://github.com/sentinel-hub/sentinelhub-py), remove dependency on the specified  `opencv-python` version in `requirements.txt` and install it manually. But I hope we find a better solution.

**Comment by nargiropgeo** [comment]
Yeah, so it's my fault. I was using the 3.7.0 python version which is not
compatible with any of the OpenCV versions that are currently available on
pypi. Downgraded to 3.6.5 and everything is good now. Sorry for the
inconvenience!

**Comment by AleksMat** [comment]
Great that it worked. I hope OpenCV will soon extend their support to Python 3.7.
