### ISSUE TITLE
[HELP] Cloud detector run locally is masking non-clouds

### ISSUE THREAD

**Issue by eoasker** [sentinel-hub/sentinel2-cloud-detector#80]
Hello. I am trying to use the Cloud-detector on locally stored S2-Images in .SAFE format (L1C). I ran the cloud detector for 3 images. One of them masked quite well the clouds. However when I ran the same code for two other images with almost no clouds in the image, the cloud mask that is returned comes completely wrong.
Is there something wrong in my code? Or is this a problem with the detection?

This is the code I am running: 
 ```python
        #run s2cloudless
        #initialize s2cloudless
        cloud_detector = S2PixelCloudDetector(threshold=0.4, average_over=4, dilation_size=2)
        print("Resampling bands to 10 meters...")
        with rasterio.open(f"{output_clip}/{jp2_name}_B02.jp2") as img:
            B02 = img.read()
            tmparr = np.empty_like(B02)
            aff = img.transform
        with rasterio.open(f"{output_clip}/{jp2_name}_B04.jp2") as img:
            B04 = img.read()         
        with rasterio.open(f"{output_clip}/{jp2_name}_B08.jp2") as img:
            B08 = img.read()
        with rasterio.open(f"{output_clip}/{jp2_name}_B01.jp2") as img:
            B01 = img.read()
            reproject(
                B01, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B01 = tmparr            
        with rasterio.open(f"{output_clip}/{jp2_name}_B05.jp2") as img:
            B05 = img.read()
            reproject(
                B05, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B05 = tmparr            
        with rasterio.open(f"{output_clip}/{jp2_name}_B8A.jp2") as img:
            B8A = img.read()
            reproject(
                B8A, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B8A = tmparr            
        with rasterio.open(f"{output_clip}/{jp2_name}_B09.jp2") as img:
            B09 = img.read()
            reproject(
                B09, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B09 = tmparr              
        with rasterio.open(f"{output_clip}/{jp2_name}_B10.jp2") as img:
            B10 = img.read()
            reproject(
                B10, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B10 = tmparr            
        with rasterio.open(f"{output_clip}/{jp2_name}_B11.jp2") as img:
            B11 = img.read()
            reproject(
                B11, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B11 = tmparr             
        with rasterio.open(f"{output_clip}/{jp2_name}_B12.jp2") as img:
            B12 = img.read()
            reproject(
                B12, tmparr,
                src_transform = img.transform,
                dst_transform = aff,
                src_crs = img.crs,
                dst_crs = img.crs,
                resampling = Resampling.bilinear)
            B12 = tmparr                   
                                                        
        bands = np.array([np.dstack((B01[0]/10000.0,B02[0]/10000.0,B04[0]/10000.0,B05[0]/10000.0,B08[0]/10000.0,B8A[0]/10000.0,B09[0]/10000.0,B10[0]/10000.0,B11[0]/10000.0,B12[0]/10000.0))])
        
        #run s2cloudless
        print("Running s2cloudless..")
        cloud_probs = cloud_detector.get_cloud_probability_maps(bands)
        mask = cloud_detector.get_cloud_masks(bands).astype(rasterio.uint8)
        
        print("Saving cloud mask as raster..")
        #save clouds mask
        with rasterio.open(f"{output_mask}/cloud_mask.tif", "w",  driver='GTiff',height=mask.shape[1],width=mask.shape[2],count=1,dtype=rasterio.uint8,crs=CRS,transform=aff) as dest:
            dest.write(mask)
        with rasterio.open(f"{output_mask}/cloud_probability_mask.tif", "w",  driver='GTiff',height=cloud_probs.shape[1],width=cloud_probs.shape[2],count=1,dtype=cloud_probs.dtype,crs=CRS,transform=aff) as dest:
            dest.write(cloud_probs)

```
The image I am showing you below is _S2A_MSIL1C_20231004T113321_N0509_R080_T29TNF_20231004T151316.SAFE_ and I have clipped it around the district of Porto.
This is the RGB composite and the mask cloud for the same image:
![image](https://github.com/sentinel-hub/sentinel2-cloud-detector/assets/153724567/f418f72f-959e-4e62-bf34-3ab126393f7a)

![image](https://github.com/sentinel-hub/sentinel2-cloud-detector/assets/153724567/63306ebd-807b-4595-a724-26f6843b607e)

**Comment by mlubej** [comment]
Hi @eoasker,

can you provide some info, please:
- what is the shape of the `bands` object? (`bands.shape`)
- what is the shape of the `mask` object? (`mask.shape`)

Are you plotting masks or cloud probabilities above a certain threshold?

**Comment by eoasker** [comment]
Hi @mlubej . So the bands shape is ```(1, 5210, 7660, 10)``` and the mask shape is ```(1, 5210, 7660)``` . I am opening the mask and cloud probability on qgis, where for the mask the min and max is 0 and 1 which is the image I am showing you above.

**Comment by mlubej** [comment]
OK, it looks like the shapes are correct. Can you use the info tool on the black and white areas to check the values of the tiff if they are correct? I'm suspicious of this being a `no_data` issue, where the 0 values of the mask were tagged as no_data automatically.

Try setting the nodata to -1 in qgis manually, or add a specific value when you save the tiff.

Let me know if this solves the issue.

**Comment by eoasker** [comment]
So in qgis I set to -1 and nothing changed. I added this line to my code so any nodata values would be =255 but the ouput image is equal to the previous one. 
```python
profile.update(nodata=nodata_value)
data[data == src.nodata] = nodata_value
```
I though this was strange since I am clipping my image and the background should be nodata right? I also tried to run for the whole image but the mask returned came with the same problem (I will put the images at the end).

I attached the full code as well the AOI if you wish to try and run the code. I cannot attach the image because of the size limit but it is _S2A_MSIL1C_20231004T113321_N0509_R080_T29TNF_20231004T151316. Just put the image zip inside the images_download folder.
  

I pretty sure I am missing something in my code..ing something in my code, not sure what.
![image](https://github.com/sentinel-hub/sentinel2-cloud-detector/assets/153724567/cd77d093-ffbf-4bdb-a623-8d488edbb70e)
![image](https://github.com/sentinel-hub/sentinel2-cloud-detector/assets/153724567/782f4ab9-4d3b-4b92-93fd-765d69706858)
[cloud_detector.zip](https://github.com/sentinel-hub/sentinel2-cloud-detector/files/13674462/cloud_detector.zip)

**Comment by eoasker** [comment]
I have solved the problem. While I was dividing the bands by 10000.0 I also needed to remove the offset from them as seen [here](https://github.com/sentinel-hub/sentinel2-cloud-detector/issues/25#issuecomment-1453475021) . I also made sure that there were no negative values. Thank you for the help.
