### ISSUE TITLE
[HELP] Error when using s2cloudless installed with conda in headless context

### ISSUE THREAD

**Issue by pierre-manchon** [sentinel-hub/sentinel2-cloud-detector#85]
**Question**

I am implementing tests in a pipeline using conda environements in docker images and wondered why I got this error:
`ImportError: libEGL.so.1: cannot open shared object file: No such file or directory`.

Is it normal that the `opencv-python-headless` dependency declared in [pyproject.toml](https://github.com/sentinel-hub/sentinel2-cloud-detector/blob/f5d1931fe11f3469cdb6fb58af704bea54a75113/pyproject.toml#L37-L41) differ from the one declared in the [feedstock's recipe.yaml](https://github.com/conda-forge/s2cloudless-feedstock/blob/22aefa70d0fb0fb05f94aa8408d3fa8ba4bdc9b7/recipe/meta.yaml#L23-L28) (`opencv`) ?

**Additional context**

```text
s2cloudless: 1.7.2

lightbgm: 4.5.0
numpy: 1.26.4
opencv: 4.10.0
sentinelhub: 3.10.3
typing-extensions: 4.21.2
```

**Comment by zigaLuksic** [comment]
The packages on conda are not completely the same as on PyPI, so some names differ.

When we were configuring the feedstock we had to add `mesa-libGL` as a [system level requirement](https://github.com/conda-forge/s2cloudless-feedstock/blob/22aefa70d0fb0fb05f94aa8408d3fa8ba4bdc9b7/recipe/yum_requirements.txt) though i am not sure if that fixes the problem in your case

**Comment by pierre-manchon** [comment]
> The packages on conda are not completely the same as on PyPI, so some names differ.
> 
> When we were configuring the feedstock we had to add `mesa-libGL` as a [system level requirement](https://github.com/conda-forge/s2cloudless-feedstock/blob/22aefa70d0fb0fb05f94aa8408d3fa8ba4bdc9b7/recipe/yum_requirements.txt) though i am not sure if that fixes the problem in your case

Hello @zigaLuksic, thanks for the response,

It didn't fix my problem however I overcame it by specifying to conda that it should use pip to install s2cloudless in my headless environment and not conda.

Thanks,
Pierre
