### ISSUE TITLE
i do not have any error ,but all of  mask =1 ,all of prob=0.9976,that's why? help please

### ISSUE THREAD

**Issue by yolo-yolo** [sentinel-hub/sentinel2-cloud-detector#86]
**Resources**

Before opening an issue for help/support, make sure you have checked [existing issues](https://github.com/sentinel-hub/sentinel2-cloud-detector/issues) and the Sentinel Hub [forum](https://forum.sentinel-hub.com/).

**Question**

Formulate your question in a clear and structured way, providing context and links to the resources raising issues.

NOTE: Remove any confidential information, such as Sentinel Hub credentials!

**Additional context**

Add any information that would help us supporting you.

**Comment by zigaLuksic** [comment]
Hi @yolo-yolo, could you provide us with some of  the data for which you get the above result?

**Comment by yolo-yolo** [comment]
Thanks for your reply. My problem has been solved. The problem is mainly due to a small problem in the processing step of the input data. Best wishes！







---- Replied Message ----
| From | Žiga ***@***.***> |
| Date | 8/26/2024 14:25 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [sentinel-hub/sentinel2-cloud-detector] i do not have any error ,but all of mask =1 ,all of prob=0.9976,that's why? help please (Issue #86) |

Hi @yolo-yolo, could you provide us with some of the data for which you get the above result?
