### ISSUE TITLE
Overlay Cloud Mask problem

### ISSUE THREAD

**Issue by Waasil** [sentinel-hub/sentinel2-cloud-detector#9]
Hello ,

I wanted to start using sentinel2-cloud-detector. Firstly I wanted get to know how it works. I rewrite code from Example and I cant pass through first visualisation. In my example there is no RGB true color scene below cloud mask. You can see image of the problem under. On the left is correct overlay in documentation, on the right is mine product. May you have an idea why there is not? 

![image](https://user-images.githubusercontent.com/20801127/43842830-78fb535a-9b26-11e8-9eb8-721e269f6455.png)

I will be very thankful for help.

**FIXED:**

![image](https://user-images.githubusercontent.com/20801127/43889247-f6ce297c-9bc3-11e8-8872-9f321bfec935.png)

**Comment by mlubej** [comment]
Thanks @Waasil for spotting the inconsistency, we will fix the example script.

**Comment by mlubej** [comment]
Issue fixed.
